### PR TITLE
Implementing class objects and methods

### PR DESCRIPTION
**Pull request by tomasesquivelgc**
## What's new in this branch:

 - bookList and Books are now classes instead of objects.
 - every function regarding adding, removing, and printing (displaying the new array in the HTML) are now methods of the 'List' class.
 - CSS implemented to resemble the template.
 - Form value now resets with the 'add' button.

### CODE REVIEW

**Review by danmainah — CHANGES_REQUESTED** [review]
Hi @tomasesquivelgc and @enmanuelbayen  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design


# Required Changes ♻️

- [ ] @team great work on your app, everything is functioning properly, however, your issue link is not working, kindly check on the link, it seems the link is redirecting to non existing page and not the issue  page as it should do
image


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by enmanuelbayen** [comment]
@danmainah  Hi! Thanks for the quick feedback. 
Just want to ask what you mean by the issues link.

**Comment by danmainah** [comment]
> @danmainah Hi! Thanks for the quick feedback. Just want to ask what you mean by the issues link.
@enmanuelbayen the link to your issue page

**Comment by enmanuelbayen** [comment]
- PR suggestion fix
Little explanation of my initial doubts about the above-mentioned in the review.
https://www.loom.com/share/4d7ee0580d274221be7c9b3ac623e119

**Review by KanzaTahreem — APPROVED** [review]
# Approved 🥳

Hi @enmanuelbayen & @tomasesquivelgc  👋

Great job implementing the changes suggested by the reviewer 💪

**_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**



## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ Great work using the right GitHub Flow 
-  ✅ Your README looks professional, well done!
-  ✅ Linters are working properly, great job! 

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Please consider adding commit messages in **imperative tense and capitalized.**  [Read more about how to write descriptive commit messages.](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8) 🔗 You can follow this article to learn more about [maintaining a professional repo](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) 💡
- [OPTIONAL] I think it would be better to remove the following arrows from your README 👇 I think these are left by mistake, what do you think about removing them? 💭

image

 
Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
